export const dummyMembers = [
	{
		memberId: 10,
		loginId: 'member10',
		password: 'password123',
		email: 'kimcoding@gmail.com',
		nickname: 'member10',
		country: 'Korea',
	},
	{
		memberId: 9,
		loginId: 'member9',
		password: 'password123',
		email: 'kimcoding@gmail.com',
		nickname: 'member9',
		country: 'Korea',
	},
	{
		memberId: 8,
		loginId: 'member8',
		password: 'password123',
		email: 'kimcoding@gmail.com',
		nickname: 'member8',
		country: 'Korea',
	},
	{
		memberId: 7,
		loginId: 'member7',
		password: 'password123',
		email: 'kimcoding@gmail.com',
		nickname: 'member7',
		country: 'Korea',
	},
	{
		memberId: 6,
		loginId: 'member6',
		password: 'password123',
		email: 'kimcoding@gmail.com',
		nickname: 'member6',
		country: 'Korea',
	},
	{
		memberId: 5,
		loginId: 'member5',
		password: 'password123',
		email: 'kimcoding@gmail.com',
		nickname: 'member5',
		country: 'Korea',
	},
	{
		memberId: 4,
		loginId: 'member4',
		password: 'password123',
		email: 'kimcoding@gmail.com',
		nickname: 'member4',
		country: 'Korea',
	},
	{
		memberId: 3,
		loginId: 'member3',
		password: 'password123',
		email: 'kimcoding@gmail.com',
		nickname: 'member3',
		country: 'Korea',
	},
	{
		memberId: 2,
		loginId: 'member2',
		password: 'password123',
		email: 'kimcoding@gmail.com',
		nickname: 'member2',
		country: 'Korea',
	},
	{
		memberId: 1,
		loginId: 'member1',
		password: 'password123',
		email: 'kimcoding@gmail.com',
		nickname: 'member1',
		country: 'Korea',
	},
];
